/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

 module.exports = {
    sidebar: [
      {
        type: 'category',
        label: 'Getting started',
  //      collapsed: false,
        items: [
            'getting-started/introduction',
            'getting-started/integrations',
            'getting-started/supported-platforms',
            {
              type: 'category',
              label: 'Deployment options',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'getting-started/installation'
                },
              ],
            },
        ],
      },
      {
          type: 'category',
          label: 'Concepts',
          collapsed: false,
          items: [
                {
                  type: 'category',
                  label: 'Netdata architecture',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'concepts/netdata-architecture'
                    },
                  ],
                },
                {
                  type: 'category',
                  label: 'Netdata Agent',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'concepts/netdata-agent'
                    },
                  ],
                },
                {
                  type: 'category',
                  label: 'Netdata Cloud',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'concepts/netdata-cloud'
                    },
                  ],
                },
                {
                  type: 'category',
                  label: 'Guided troubleshooting',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'concepts/guided-troubleshooting'
                    },
                  ],
                },
                {
                  type: 'category',
                  label: 'Visualizations',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'concepts/visualizations'
                    },
                  ],
                },
                {
                  type: 'category',
                  label: 'Health monitoring',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'concepts/health-monitoring'
                    },
                  ],
                },
                'concepts/glossary',
              ]
        },
        {
          type: 'category',
          label: 'Setup',
          collapsed: false,
          items: [
                'setup/sign-in-to-netdata',
                'setup/setup-your-space-and-rooms',
                'setup/deploy-the-agent',
                'setup/claim-existing-agent-to-the-cloud',
                'setup/agent-configuration',
                {
                  type: 'category',
                  label: 'Space administration',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'setup/space-administration'
                    },
                  ],
                },
              ]
        },
        {
          type: 'category',
          label: 'Operations',
         collapsed: false,
          items: [
              {
                type: 'autogenerated',
                dirName: 'operations'
              },
           ]
        },
        {
          type: 'category',
          label: 'References',
          collapsed: false,
          items: [
              {
                type: 'category',
                label: 'General References',
                items: [
                  {
                    type: 'autogenerated',
                    dirName: 'references/general-references/configuration-references'
                  },
                ],
              },
              'references/general-references/agent-cli',
              'references/general-references/notifications-reference',
              {
                type: 'category',
                label: 'Collectors References',
                items: [
                  {
                    type: 'autogenerated',
                    dirName: 'references/collectors-references'
                  },
                ],
              },
          ],
        },
    ]
  };
  