# section: static << START

[build]
  command = "npm run build:netlify"
  publish = "build"
  environment = { NPM_VERSION = "10.9.2", NODE_VERSION = "22.14.0", NETLIFY_USE_YARN = "true", NODE_OPTIONS = "--max-old-space-size=8192"}

[[plugins]]
  package = "./plugins/netlify-plugin-indexnow"

  [plugins.inputs]
    host = "learn.netdata.cloud"
    key = "69893e732658435694bf647d5a6fed1d"
    keyLocation = "https://learn.netdata.cloud/69893e732658435694bf647d5a6fed1d.txt"


[[redirects]]
  from="/guides/monitor/kubernetes-k8s-netdata"
  to="/docs/dashboards-and-charts/tabs/kubernetes"

[[redirects]]
  from="/docs/network-flows"
  to="/docs/network-performance-monitoring/network-flows"

[[redirects]]
  from="/docs/network-flows/*"
  to="/docs/network-performance-monitoring/network-flows/:splat"

[[redirects]]
  from="/docs/netdata-agent/configuration/cheatsheet"
  to="/docs/netdata-agent/configuration/"

[[redirects]]
  from="/docs/developer-and-contributor-corner/monitor-pi-hole-and-a-raspberry-pi-with-netdata"
  to="/docs/netdata-agent/installation/"

[[redirects]]
  from="/docs/developer-and-contributor-corner/build-a-custom-dashboard-html-page"
  to="/docs/dashboards-and-charts/tabs/dashboards"

[[redirects]]
  from="/docs/data-collection/monitor-anything/system-metrics/windows-machines"
  to="/docs/netdata-agent/installation/windows"

[[redirects]]
  from="/docs/collect/system-metrics"
  to="/docs/collecting-metrics/"

[[redirects]]
  from="/docs/collect/container-metrics"
  to="/docs/collecting-metrics/collectors/containers-and-vms"

[[redirects]]
  from="/docs/rest-api/netdata-badges"
  to="/api"

[[redirects]]
  from="/docs/agent/web/api/badges/"
  to="/api"

[[redirects]]
  from="/docs/agent/collectors/python.d.plugin/springboot"
  to="/docs/collecting-metrics"

[[redirects]]
  from="/docs/agent/collectors/python.d.plugin/alarms"
  to="/docs/collecting-metrics"

[[redirects]]
  from="/docs/agent/collectors/python.d.plugin/anomalies"
  to="/docs/collecting-metrics"

[[redirects]]
  from="/docs/agent/collectors/proc.plugin"
  to="/docs/collecting-metrics"

[[redirects]]
  from="/docs/agent/collectors/cgroups.plugin"
  to="/docs/collecting-metrics/containers-and-cgroups"

[[redirects]]
  from="/docs/agent/collectors/node.d.plugin/"
  to="/docs/collecting-metrics"

[[redirects]]
  from="/docs/agent/collectors/go.d.plugin/modules/wmi"
  to="/docs/netdata-agent/installation/windows"

[[redirects]]
  from="/docs/data-collection/monitor-anything/System%20Metrics/Windows-machines"
  to="/docs/netdata-agent/installation/windows"

[[redirects]]
  from="/docs/data-collection/windows-systems"
  to="/docs/netdata-agent/installation/windows"

[[redirects]]
  from="/docs/data-collection/windows-systems/windows"
  to="/docs/netdata-agent/installation/windows"

[[redirects]]
  from="/docs/nightly/operations/alerts/add-opsgenie-notification-configuration"
  to="/docs/alerts-&-notifications/notifications/centralized-cloud-notifications/opsgenie"

[[redirects]]
  from="/docs/agent/changelog"
  to="https://github.com/netdata/netdata/blob/master/CHANGELOG.md"

[[redirects]]
  from="/docs/nightly/concepts/netdata-functions"
  to="/docs/live-view"

[[redirects]]
  from="/docs/nightly/concepts/netdata-plans"
  to="/docs/netdata-cloud/netdata-plans-&-billing"

[[redirects]]
  from="/docs/nightly/concepts/role-based-access-model"
  to="/docs/netdata-cloud/authentication-&-authorization/role-based-access-model"

[[redirects]]
  from="/docs/nightly/operations/alerts/add-discord-notification-configuration"
  to="/docs/alerts-&-notifications/notifications/centralized-cloud-notifications/discord"

[[redirects]]
  from="/docs/nightly/operations/alerts/add-webhook-notification-configuration"
  to="/docs/alerts-&-notifications/notifications/centralized-cloud-notifications/webhook"

[[redirects]]
  from="/docs/nightly/operations/alerts/add-pagerduty-notification-configuration"
  to="/docs/alerts-&-notifications/notifications/centralized-cloud-notifications/pagerduty"

[[redirects]]
  from="/docs/nightly/operations/alerts/add-slack-notification-configuration"
  to="/docs/alerts-&-notifications/notifications/centralized-cloud-notifications/slack"

[[redirects]]
  from="/docs/nightly/operations/run-time-troubleshooting-with-functions"
  to="/docs/live-view"

[[redirects]]
  from="/docs/nightly/troubleshooting-and-machine-learning/events-feed"
  to="/docs/dashboards-and-charts/tabs/events"

[[redirects]]
  from="/docs/nightly/troubleshooting-and-machine-learning/functions"
  to="/docs/live-view"

[[redirects]]
  from="/docs/nightly/getting-started/monitor-your-infrastructure/netdata-plans"
  to="/docs/netdata-cloud/netdata-plans-&-billing"

[[redirects]]
  from="/docs/nightly/deployment-in-production/security/role-based-access-model"
  to="/docs/netdata-cloud/authentication-&-authorization/role-based-access-model"

[[redirects]]
  from="/docs/nightly/alerts-and-notifications/notifications/cloud-alert-notifications/add-discord-notification-configuration"
  to="/docs/alerts-&-notifications/notifications/centralized-cloud-notifications/discord"

[[redirects]]
  from="/docs/nightly/alerts-and-notifications/notifications/cloud-alert-notifications/add-webhook-notification-configuration"
  to="/docs/alerts-&-notifications/notifications/centralized-cloud-notifications/webhook"

[[redirects]]
  from="/docs/nightly/alerts-and-notifications/notifications/cloud-alert-notifications/add-pagerduty-notification-configuration"
  to="/docs/alerts-&-notifications/notifications/centralized-cloud-notifications/pagerduty"

[[redirects]]
  from="/docs/nightly/alerts-and-notifications/notifications/cloud-alert-notifications/add-slack-notification-configuration"
  to="/docs/alerts-&-notifications/notifications/centralized-cloud-notifications/slack"

[[redirects]]
  from="/docs/nightly/troubleshooting-and-machine-learning/run-time-troubleshooting-with-functions"
  to="/docs/live-view"

[[redirects]]
  from="/guides"
  to="/docs/getting-started"

[[redirects]]
  from="/docs/collecting-metrics/windows-systems/windows"
  to="/docs/netdata-agent/installation/windows"

[[redirects]]
  from="/docs/agent/cheatsheet"
  to="/docs/netdata-agent/configuration"

[[redirects]]
  from="/docs/cloud/monitoring/alarms"
  to="/docs/dashboards-and-charts/tabs/alerts"

[[redirects]]
  from="/docs/cloud/monitor/alarms"
  to="/docs/dashboards-and-charts/tabs/alerts"

[[redirects]]
  from="/docs/visualize/view-all-nodes"
  to="/docs/dashboards-and-charts/tabs/nodes"

[[redirects]]
  from="/docs/agent/contributors"
  to="/docs/developer-and-contributor-corner/contributing"

[[redirects]]
  from="/docs/agent/packaging/DISTRIBUTIONS"
  to="/docs/netdata-agent/versions-&-platforms"

[[redirects]]
  from="/docs/agent/collectors/python.d.plugin/energid"
  to="/docs/collecting-metrics"

[[redirects]]
  from="/docs/agent/collectors/python.d.plugin/ntpd"
  to="/docs/collecting-metrics/collectors/networking/ntpd"

[[redirects]]
  from="/docs/agent/zh/collectors/python.d.plugin/exim"
  to="/docs/collecting-metrics/collectors/applications/exim"

[[redirects]]
  from="/docs/agent/zh/collectors/python.d.plugin/tomcat"
  to="/docs/collecting-metrics/collectors/web-servers-and-proxies/tomcat"

[[redirects]]
  from="/docs/agent/zh/docs/step-by-step/step-00"
  to="/docs/netdata-agent/quickstart-deployment"

[[redirects]]
  from="/docs/agent/zh/libnetdata/eval"
  to="/docs/developer-and-contributor-corner/libnetdata"

[[redirects]]
  from="/docs/agent/zh/packaging/installer/methods/manual"
  to="/docs/developer-and-contributor-corner/install-the-netdata-agent-from-a-git-checkout"

[[redirects]]
  from="/docs/agent/zh/web/api/queries/ses"
  to="/docs/developer-and-contributor-corner/rest-api/queries/single-or-simple-exponential-smoothing-ses"

# section: static << END
