"""Build Learn's /llms.txt and /llms-full.txt from the ingested docs.

llms-full.txt is the Complete Product Description as plain markdown with absolute links.
llms.txt indexes it and the hand-written documentation in sidebar order. Integration catalogs
appear once, through their overview page, instead of one entry per generated integration page,
which keeps the index small enough for one model context.
"""

import re
from pathlib import Path

from learn_links import split_front_matter

SITE = "https://learn.netdata.cloud"
PRODUCT_DESCRIPTION_SOURCE = "/docs/netdata-complete-product-description.md"
GENERATED_INTEGRATION_MARKER = "DO NOT EDIT THIS FILE DIRECTLY"
PAGINATION_CLASS = "generated-pagination-page"

_INLINE_CODE = re.compile(r"(`+)(?:(?!\1).)+?\1")
_MDX_ESCAPE = re.compile(r"\\([{}<])")
_SITE_RELATIVE_LINK = re.compile(r"\]\((/(?!/)[^)\s]*)")
_SITE_RELATIVE_HREF = re.compile(r"""(\bhref\s*=\s*["'])(/(?!/)[^"']*)""")


def _read(path, read_text):
    if read_text is not None:
        return read_text(path)
    return Path(path).read_text(encoding="utf-8")


def _transform_prose(body, transform):
    """Apply transform to prose only; code blocks and inline code stay byte for byte."""
    output = []
    fence = None
    for line in body.split("\n"):
        stripped = line.strip()
        if fence is not None:
            if stripped and set(stripped) == {fence[0]} and len(stripped) >= len(fence):
                fence = None
            output.append(line)
            continue
        opening = re.match(r"(`{3,}|~{3,})", stripped)
        if opening:
            fence = opening.group(1)
            output.append(line)
            continue
        pieces = []
        position = 0
        for code in _INLINE_CODE.finditer(line):
            pieces.append(transform(line[position : code.start()]))
            pieces.append(code.group(0))
            position = code.end()
        pieces.append(transform(line[position:]))
        output.append("".join(pieces))
    return "\n".join(output)


def _plain_markdown(text):
    text = _MDX_ESCAPE.sub(r"\1", text)
    text = _SITE_RELATIVE_LINK.sub(lambda match: "](" + SITE + match.group(1), text)
    return _SITE_RELATIVE_HREF.sub(lambda match: match.group(1) + SITE + match.group(2), text)


def llms_full_text(body):
    """Turn an ingested page body back into plain markdown with absolute links."""
    return _transform_prose(body, _plain_markdown).strip("\n") + "\n"


def _summary(body):
    lines = body.split("\n")
    for index, line in enumerate(lines):
        if line.strip().lower() == "## executive summary":
            paragraph = []
            for candidate in lines[index + 1 :]:
                if candidate.strip():
                    if candidate.startswith("#"):
                        break
                    paragraph.append(candidate.strip())
                elif paragraph:
                    break
            return " ".join(paragraph)
    return ""


def _one_line(value):
    return " ".join(str(value or "").split())


def _position(front_matter):
    try:
        return int(str(front_matter.get("sidebar_position")).strip())
    except (TypeError, ValueError):
        return None


def _label(front_matter, fallback):
    label = _one_line(front_matter.get("sidebar_label") or front_matter.get("title") or fallback)
    return label.replace("[", "(").replace("]", ")")


def _is_product_description(front_matter):
    return str(front_matter.get("custom_edit_url") or "").endswith(PRODUCT_DESCRIPTION_SOURCE)


def _is_indexed(front_matter):
    if (
        _is_product_description(front_matter)
        or "part_of_learn" in front_matter
        or not front_matter.get("learn_link")
    ):
        return False
    if front_matter.get("generated_grid_page") is True:
        return front_matter.get("sidebar_class_name") != PAGINATION_CLASS
    return (
        front_matter.get("learn_status") == "Published"
        and GENERATED_INTEGRATION_MARKER not in str(front_matter.get("message") or "")
    )


def _sort_key(front_matter, label):
    position = _position(front_matter)
    return (position is None, position or 0, label.lower())


def _ordered_items(directory, front_matters):
    """Return the sidebar children of a directory: (kind, path, front matter, label)."""
    items = []
    for child in directory.iterdir():
        if child.is_dir():
            index = child / f"{child.name}.mdx"
            front_matter = front_matters.get(index, {})
            label = _label(front_matter, child.name)
            items.append((_sort_key(front_matter, label), "category", child, front_matter, label))
        elif child.suffix == ".mdx" and child.stem != directory.name:
            front_matter = front_matters.get(child, {})
            label = _label(front_matter, child.stem)
            items.append((_sort_key(front_matter, label), "page", child, front_matter, label))
    items.sort(key=lambda item: item[0])
    return [item[1:] for item in items]


def _entry(front_matter, label):
    line = f"- [{label}]({front_matter['learn_link']})"
    description = _one_line(front_matter.get("description"))
    return f"{line}: {description}" if description else line


def _section_entries(directory, front_matters, crumbs):
    entries = []
    index = directory / f"{directory.name}.mdx"
    index_front_matter = front_matters.get(index)
    if index_front_matter is not None and _is_indexed(index_front_matter):
        label = " › ".join(crumbs) if crumbs else _label(index_front_matter, directory.name)
        entries.append(_entry(index_front_matter, label))
    for kind, path, front_matter, label in _ordered_items(directory, front_matters):
        if kind == "category":
            entries.extend(_section_entries(path, front_matters, crumbs + [label]))
        elif _is_indexed(front_matter):
            entries.append(_entry(front_matter, " › ".join(crumbs + [label])))
    return entries


def build_llms_files(docs_root, read_text=None):
    """Return (llms.txt, llms-full.txt) contents, or None when the product description is missing."""
    docs_root = Path(docs_root)
    front_matters = {}
    product_description = None
    for path in sorted(docs_root.rglob("*.mdx")):
        front_matter, body = split_front_matter(_read(path, read_text))
        front_matters[path] = front_matter
        if _is_product_description(front_matter):
            product_description = (front_matter, body)
    if product_description is None:
        return None

    description_front_matter, description_body = product_description
    full = llms_full_text(description_body)
    summary = _one_line(_summary(full))

    lines = ["# Netdata", ""]
    if summary:
        lines += [f"> {summary}", ""]
    lines += [
        "This index lists the Netdata documentation on learn.netdata.cloud in sidebar order. "
        "The Complete Product Description describes everything Netdata does in one file, "
        "with links to the pages below.",
        "",
        "## Complete Product Description",
        "",
        f"- [Complete Product Description]({SITE}/llms-full.txt): "
        + _one_line(description_front_matter.get("description")),
        f"- [Complete Product Description web page]({description_front_matter['learn_link']})",
    ]
    for kind, path, front_matter, label in _ordered_items(docs_root, front_matters):
        entries = (
            _section_entries(path, front_matters, [])
            if kind == "category"
            else ([_entry(front_matter, label)] if _is_indexed(front_matter) else [])
        )
        if entries:
            lines += ["", f"## {label}", ""] + entries
    return "\n".join(lines) + "\n", full
