import tempfile
import unittest
from pathlib import Path

import ingest


class SeoGridGenerationTests(unittest.TestCase):
    def test_only_oversized_indexes_are_paginated(self):
        self.assertEqual(ingest._grid_page_count(400), 1)
        self.assertEqual(ingest._grid_page_count(401), 3)
        self.assertEqual(ingest._grid_page_count(807), 5)

    def test_set_html_attr_replaces_existing_value_without_duplicates(self):
        tag = '<img src="logo.svg" alt="old"/>'
        self.assertEqual(
            ingest._set_html_attr(tag, "alt", ""),
            '<img src="logo.svg" alt=""/>',
        )

    def test_rendered_pages_have_unique_metadata_and_crawlable_pagination(self):
        pages = [
            ingest._render_grid_page(
                "Collectors",
                'sidebar_position: "10"',
                "collecting-metrics/collectors",
                "Browse Netdata collectors.",
                [f"<Box>{page_number}</Box>"],
                page_number,
                3,
            )
            for page_number in range(1, 4)
        ]

        self.assertIn('slug: "/collecting-metrics/collectors"', pages[0])
        self.assertIn('slug: "/collecting-metrics/collectors/page/2"', pages[1])
        self.assertIn("# Collectors (page 3)", pages[2])
        self.assertIn("Page 2 of 3", pages[1])
        for page_number, page in enumerate(pages, start=1):
            self.assertIn(
                f'currentPage={{{page_number}}} pageCount={{3}}',
                page,
            )

    def test_generated_grid_detection_rejects_authored_content(self):
        with tempfile.TemporaryDirectory() as directory:
            generated = Path(directory) / "generated.mdx"
            generated.write_text(
                'learn_status: "AUTOGENERATED"\n'
                "import { Grid } from '@site/src/components/Grid_integrations';\n",
                encoding="utf-8",
            )
            authored = Path(directory) / "authored.mdx"
            authored.write_text("# Authored\n", encoding="utf-8")
            self.assertTrue(ingest._is_generated_grid_page(generated))
            self.assertFalse(ingest._is_generated_grid_page(authored))


if __name__ == "__main__":
    unittest.main()
