import hashlib
import json
import os
import re
import shutil
import tempfile
import unittest
from pathlib import Path

import ingest


class SeoGridGenerationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.repository_root = Path(__file__).resolve().parents[1]
        repository_docs = cls.repository_root / "docs"
        generated_output_ready = (
            ingest.SIDEBAR_ORDER_STATE_PATH.is_file()
            and ingest._sidebar_state_checksum_path(
                ingest.SIDEBAR_ORDER_STATE_PATH
            ).is_file()
        )
        cls._generated_fixture = None
        if generated_output_ready:
            cls.source_docs = repository_docs
            payload = json.loads(
                ingest.SIDEBAR_ORDER_STATE_PATH.read_text(encoding="utf-8")
            )
            cls.sidebar_order = {
                (entry["parent_path"], entry["child_name"]): entry["position"]
                for entry in payload["order"]
            }
        else:
            cls._generated_fixture = tempfile.TemporaryDirectory()
            cls.source_docs = Path(cls._generated_fixture.name) / "docs"
            shutil.copytree(repository_docs, cls.source_docs)
            legacy_grids = []
            for candidate in sorted(cls.source_docs.rglob("*.mdx")):
                text = candidate.read_text(encoding="utf-8")
                if (
                    'learn_status: "AUTOGENERATED"' in text
                    and "from '@site/src/components/Grid_integrations'" in text
                ):
                    legacy_grids.append(candidate)
            if len(legacy_grids) != 26:
                raise AssertionError(
                    f"Expected 26 legacy generated grids, found {len(legacy_grids)}"
                )
            for legacy_grid in legacy_grids:
                legacy_grid.unlink()

            cls.sidebar_order = {("root", "__test_fixture__"): 10}
            ingest.MAP_SIDEBAR_ORDER.clear()
            ingest.MAP_SIDEBAR_ORDER.update(cls.sidebar_order)
            ingest.reconcile_generated_outputs(cls.source_docs, netlify_path=None)

    @classmethod
    def tearDownClass(cls):
        if cls._generated_fixture is not None:
            cls._generated_fixture.cleanup()

    def setUp(self):
        ingest.MAP_SIDEBAR_ORDER.clear()
        ingest.MAP_SIDEBAR_ORDER.update(self.sidebar_order)
        ingest.MAP_DOC_SCOPE.clear()

    def _snapshot(self, root):
        return {
            path.relative_to(root).as_posix(): hashlib.sha256(
                path.read_bytes()
            ).hexdigest()
            for path in sorted(Path(root).rglob("*"))
            if path.is_file()
        }

    def _generated_grids(self, root):
        return [
            path
            for path in sorted(Path(root).rglob("*.mdx"))
            if ingest._is_generated_grid_page(path)
        ]

    def _strip_owned_outputs(self, root):
        for path in self._generated_grids(root):
            path.unlink()
        for path in sorted(Path(root).rglob("_category_.json")):
            if ingest._is_generated_category_file(path):
                path.unlink()

    def _integration_files(self, root, relative_directory):
        directory = Path(root) / relative_directory
        return [
            path
            for path in sorted(directory.rglob("*.mdx"))
            if not ingest._is_generated_grid_page(path)
            and ingest.INTEGRATION_MARKER in path.read_text(encoding="utf-8")
        ]

    def _copy_integration(self, source, target, ordinal):
        text = Path(source).read_text(encoding="utf-8")
        text = re.sub(
            r'(?m)^sidebar_label: ".*"$',
            f'sidebar_label: "Recovery integration {ordinal}"',
            text,
            count=1,
        )
        text = re.sub(
            r'(?m)^learn_link: ".*"$',
            f'learn_link: "https://learn.netdata.cloud/docs/recovery-{ordinal}"',
            text,
            count=1,
        )
        text = re.sub(
            r'(?m)^slug: ".*"$',
            f'slug: "/recovery-{ordinal}"',
            text,
            count=1,
        )
        Path(target).write_text(text, encoding="utf-8")

    def _write_tiny_integration(self, target, ordinal):
        Path(target).write_text(
            "---\n"
            f'sidebar_label: "Synthetic {ordinal:04d}"\n'
            f'learn_link: "https://learn.netdata.cloud/docs/synthetic-{ordinal}"\n'
            f'slug: "/synthetic-{ordinal}"\n'
            "---\n"
            f"{ingest.INTEGRATION_MARKER}\n",
            encoding="utf-8",
        )

    def _redirect_fixture(self, root):
        static_path = Path(root) / "static.toml"
        netlify_path = Path(root) / "netlify.toml"
        static_path.write_text(
            "# section: static << START\n[build]\n  publish=\"build\"\n"
            "# section: static << END\n",
            encoding="utf-8",
        )
        netlify_path.write_text(
            static_path.read_text(encoding="utf-8")
            + "\n# section: dynamic << START\n"
            + "[[redirects]]\n  from=\"/docs/transition\"\n  to=\"/docs/current\"\n"
            + "# section: dynamic << END\n",
            encoding="utf-8",
        )
        return netlify_path, static_path

    def _write_state(self, docs_root, state_path, fixture_root):
        map_path = Path(fixture_root) / "map.yaml"
        map_path.write_text("sidebar: []\n", encoding="utf-8")
        ingest.write_sidebar_order_state(
            self.sidebar_order, map_path, docs_root, state_path=state_path
        )

    def _write_matching_state_checksum(self, state_path):
        checksum_path = ingest._sidebar_state_checksum_path(state_path)
        digest = hashlib.sha256(Path(state_path).read_bytes()).hexdigest()
        checksum_path.write_text(
            f"{digest}  {Path(state_path).name}\n", encoding="utf-8"
        )

    def _copy_owned_outputs(self, source, target):
        for path in self._generated_grids(source):
            destination = Path(target) / path.relative_to(source)
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, destination)
        for path in sorted(Path(source).rglob("_category_.json")):
            if ingest._is_generated_category_file(path):
                destination = Path(target) / path.relative_to(source)
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(path, destination)

    def _assert_recovery_matches_clean_full(
        self, mutate_sources, mutate_recovery=None
    ):
        with tempfile.TemporaryDirectory() as directory:
            fixture_root = Path(directory)
            clean_docs = fixture_root / "clean" / "docs"
            recovery_docs = fixture_root / "recovery" / "docs"
            shutil.copytree(self.source_docs, clean_docs)
            self._strip_owned_outputs(clean_docs)
            mutate_sources(clean_docs)

            clean_netlify, clean_static = self._redirect_fixture(
                fixture_root / "clean"
            )
            ingest.MAP_SIDEBAR_ORDER.clear()
            ingest.MAP_SIDEBAR_ORDER.update(self.sidebar_order)
            ingest.reconcile_generated_outputs(
                clean_docs,
                netlify_path=clean_netlify,
                static_path=clean_static,
            )

            shutil.copytree(clean_docs, recovery_docs)
            self._strip_owned_outputs(recovery_docs)
            self._copy_owned_outputs(self.source_docs, recovery_docs)
            if mutate_recovery is not None:
                mutate_recovery(recovery_docs)

            recovery_netlify, recovery_static = self._redirect_fixture(
                fixture_root / "recovery"
            )
            state_path = fixture_root / "state.json"
            self._write_state(clean_docs, state_path, fixture_root)
            ingest.regenerate_grids_only(
                recovery_docs,
                state_path=state_path,
                netlify_path=recovery_netlify,
                static_path=recovery_static,
            )

            self.assertEqual(self._snapshot(recovery_docs), self._snapshot(clean_docs))
            self.assertEqual(
                recovery_netlify.read_bytes(), clean_netlify.read_bytes()
            )
            first = self._snapshot(recovery_docs)
            self._write_state(recovery_docs, state_path, fixture_root)
            ingest.regenerate_grids_only(
                recovery_docs,
                state_path=state_path,
                netlify_path=recovery_netlify,
                static_path=recovery_static,
            )
            self.assertEqual(self._snapshot(recovery_docs), first)

    def test_page_count_covers_every_capacity_boundary(self):
        expected = {0: 0, 1: 1, 175: 1, 176: 2, 400: 3, 401: 3}
        self.assertEqual(
            {count: ingest._grid_page_count(count) for count in expected},
            expected,
        )

        for card_count, expected_pages in expected.items():
            with (
                self.subTest(card_count=card_count),
                tempfile.TemporaryDirectory() as directory,
            ):
                docs_root = Path(directory) / "docs"
                target = docs_root / "Synthetic"
                target.mkdir(parents=True)
                for ordinal in range(card_count):
                    self._write_tiny_integration(
                        target / f"Synthetic {ordinal:04d}.mdx", ordinal
                    )

                ingest.get_dir_make_file_and_recurse(
                    docs_root, overwrite_generated=True, docs_root=docs_root
                )
                pages = self._generated_grids(target)
                self.assertEqual(len(pages), expected_pages)
                titles = []
                for page in pages:
                    titles.extend(
                        re.findall(
                            r'<Box [^>]*title="(Synthetic \d{4})">',
                            page.read_text(encoding="utf-8"),
                        )
                    )
                self.assertEqual(len(titles), card_count)
                self.assertEqual(len(set(titles)), card_count)

    def test_set_html_attr_replaces_existing_value_without_duplicates(self):
        tag = '<img src="logo.svg" alt="old"/>'
        self.assertEqual(
            ingest._set_html_attr(tag, "alt", ""),
            '<img src="logo.svg" alt=""/>',
        )

    def test_rendered_pages_have_unique_metadata_and_crawlable_pagination(self):
        pages = [
            ingest._render_grid_page(
                "Collectors",
                'sidebar_position: "10"',
                "collecting-metrics/collectors",
                "Collectors",
                "Browse Netdata collectors.",
                [f"<Box>{page_number}</Box>"],
                page_number,
                3,
            )
            for page_number in range(1, 4)
        ]

        self.assertIn('slug: "/collecting-metrics/collectors"', pages[0])
        self.assertIn('slug: "/collecting-metrics/collectors/page/2"', pages[1])
        self.assertIn('title: "Collectors (page 2)"', pages[1])
        self.assertIn("# Collectors (page 3)", pages[2])
        self.assertIn("Page 2 of 3", pages[1])
        for page_number, page in enumerate(pages, start=1):
            self.assertIn("custom_edit_url: null", page)
            self.assertIn(
                f"currentPage={{{page_number}}} pageCount={{3}}",
                page,
            )

        device_page = ingest._render_grid_page(
            "Integrations",
            "",
            "network-performance-monitoring/device-metrics/integrations",
            "Device Metrics / Integrations",
            "Browse integrations.",
            ["<Box />"],
            2,
            2,
        )
        trap_page = ingest._render_grid_page(
            "Integrations",
            "",
            "network-performance-monitoring/snmp-traps/integrations",
            "SNMP Traps / Integrations",
            "Browse integrations.",
            ["<Box />"],
            2,
            5,
        )
        self.assertIn('title: "Device Metrics / Integrations (page 2)"', device_page)
        self.assertIn('title: "SNMP Traps / Integrations (page 2)"', trap_page)

    def test_generated_grid_ownership_requires_explicit_frontmatter_marker(self):
        with tempfile.TemporaryDirectory() as directory:
            generated = Path(directory) / "generated.mdx"
            generated.write_text(
                "---\ngenerated_grid_page: true\n---\n# Generated\n",
                encoding="utf-8",
            )
            heuristic_only = Path(directory) / "heuristic.mdx"
            heuristic_only.write_text(
                'learn_status: "AUTOGENERATED"\n'
                "import { Grid } from '@site/src/components/Grid_integrations';\n",
                encoding="utf-8",
            )
            marker_in_body = Path(directory) / "body.mdx"
            marker_in_body.write_text(
                "# Authored\n\n`generated_grid_page: true`\n",
                encoding="utf-8",
            )
            self.assertTrue(ingest._is_generated_grid_page(generated))
            self.assertFalse(ingest._is_generated_grid_page(heuristic_only))
            self.assertFalse(ingest._is_generated_grid_page(marker_in_body))

    def test_reconciliation_refuses_to_overwrite_authored_pagination_page(self):
        with tempfile.TemporaryDirectory() as directory:
            docs_root = Path(directory) / "docs"
            target = docs_root / "Synthetic"
            target.mkdir(parents=True)
            for ordinal in range(176):
                self._write_tiny_integration(
                    target / f"Synthetic {ordinal:04d}.mdx", ordinal
                )
            authored_page = target / "Synthetic Page 2.mdx"
            authored_bytes = b"---\nslug: /authored-page\n---\n# Authored page\n"
            authored_page.write_bytes(authored_bytes)

            with self.assertRaisesRegex(RuntimeError, "Refusing to overwrite"):
                ingest.get_dir_make_file_and_recurse(
                    docs_root, overwrite_generated=True, docs_root=docs_root
                )
            self.assertEqual(authored_page.read_bytes(), authored_bytes)
            self.assertFalse((target / "Synthetic.mdx").exists())

    def test_category_reconciliation_never_deletes_authored_metadata(self):
        with tempfile.TemporaryDirectory() as directory:
            docs_root = Path(directory) / "docs"
            target = docs_root / "Curated"
            target.mkdir(parents=True)
            (target / "Note.mdx").write_text("# Note\n", encoding="utf-8")
            category = target / "_category_.json"
            authored_bytes = b'{"label":"Curated","position":7}\n'
            category.write_bytes(authored_bytes)

            ingest.ensure_category_json_for_dirs(docs_root)
            self.assertEqual(category.read_bytes(), authored_bytes)
            (target / "Curated.mdx").write_text("# Curated\n", encoding="utf-8")
            ingest.ensure_category_json_for_dirs(docs_root)
            self.assertEqual(category.read_bytes(), authored_bytes)

    def test_grid_generation_rejects_dangling_and_existing_output_symlinks(self):
        for existing_target in (False, True):
            with self.subTest(existing_target=existing_target), tempfile.TemporaryDirectory() as directory:
                root = Path(directory)
                docs_root = root / "docs"
                target = docs_root / "Synthetic"
                target.mkdir(parents=True)
                self._write_tiny_integration(target / "Integration.mdx", 1)
                outside = root / "outside-grid.mdx"
                original = b"outside-authored\n"
                if existing_target:
                    outside.write_bytes(original)
                (target / "Synthetic.mdx").symlink_to(outside)

                with self.assertRaisesRegex(RuntimeError, "symbolic link"):
                    ingest.get_dir_make_file_and_recurse(
                        docs_root, overwrite_generated=True, docs_root=docs_root
                    )

                if existing_target:
                    self.assertEqual(outside.read_bytes(), original)
                else:
                    self.assertFalse(outside.exists())

    def test_category_generation_rejects_symlink_without_external_write(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            docs_root = root / "docs"
            target = docs_root / "Category"
            target.mkdir(parents=True)
            (target / "Note.mdx").write_text("# Note\n", encoding="utf-8")
            outside = root / "outside-category.json"
            (target / "_category_.json").symlink_to(outside)

            with self.assertRaisesRegex(RuntimeError, "symbolic link"):
                ingest.ensure_category_json_for_dirs(docs_root)

            self.assertFalse(outside.exists())

    def test_recovery_rejects_symlinked_directories_and_non_regular_files(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            docs_root = root / "docs"
            docs_root.mkdir()
            outside = root / "outside"
            outside.mkdir()
            marker = outside / "marker.txt"
            marker.write_text("unchanged\n", encoding="utf-8")
            (docs_root / "Linked").symlink_to(outside, target_is_directory=True)

            with self.assertRaisesRegex(RuntimeError, "symbolic link"):
                ingest.reconcile_generated_outputs(docs_root, netlify_path=None)
            self.assertEqual(marker.read_text(encoding="utf-8"), "unchanged\n")

            (docs_root / "Linked").unlink()
            fifo = docs_root / "unexpected.fifo"
            try:
                fifo.parent.mkdir(parents=True, exist_ok=True)
                os.mkfifo(fifo)
                with self.assertRaisesRegex(RuntimeError, "non-regular"):
                    ingest.reconcile_generated_outputs(docs_root, netlify_path=None)
            finally:
                if fifo.exists():
                    fifo.unlink()

    def test_grid_generation_rejects_a_starting_directory_outside_docs_root(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            docs_root = root / "docs"
            docs_root.mkdir()
            outside = root / "outside"
            outside.mkdir()
            marker = outside / "marker.txt"
            marker.write_text("unchanged\n", encoding="utf-8")

            with self.assertRaisesRegex(RuntimeError, "escapes configured docs root"):
                ingest.get_dir_make_file_and_recurse(
                    outside, overwrite_generated=True, docs_root=docs_root
                )
            self.assertEqual(marker.read_text(encoding="utf-8"), "unchanged\n")

    def test_corpus_and_state_boundaries_reject_symlinks(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            docs_root = root / "docs"
            docs_root.mkdir()
            outside_doc = root / "outside.mdx"
            outside_doc.write_text("# Outside\n", encoding="utf-8")
            (docs_root / "Linked.mdx").symlink_to(outside_doc)
            with self.assertRaisesRegex(RuntimeError, "symbolic link"):
                ingest._source_corpus_sha256(docs_root)

            (docs_root / "Linked.mdx").unlink()
            (docs_root / "Note.mdx").write_text("# Note\n", encoding="utf-8")
            state_path = root / "state.json"
            self._write_state(docs_root, state_path, root)
            outside_state = root / "outside-state.json"
            state_path.replace(outside_state)
            state_path.symlink_to(outside_state)
            with self.assertRaisesRegex(RuntimeError, "symbolic link"):
                ingest.load_sidebar_order_state(state_path, docs_root=docs_root)

    def test_state_and_redirect_outputs_reject_symlinks_before_changes(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            docs_root = root / "docs"
            docs_root.mkdir()
            note = docs_root / "Note.mdx"
            note.write_text("# Note\n", encoding="utf-8")
            map_path = root / "map.yaml"
            map_path.write_text("sidebar: []\n", encoding="utf-8")

            outside_state = root / "outside-state.json"
            outside_state.write_text("unchanged\n", encoding="utf-8")
            state_path = root / "state.json"
            state_path.symlink_to(outside_state)
            with self.assertRaisesRegex(RuntimeError, "symbolic link"):
                ingest.write_sidebar_order_state(
                    self.sidebar_order, map_path, docs_root, state_path=state_path
                )
            self.assertEqual(outside_state.read_text(encoding="utf-8"), "unchanged\n")

            state_path.unlink()
            outside_map = root / "outside-map.yaml"
            outside_map.write_text("sidebar: []\n", encoding="utf-8")
            map_path.unlink()
            map_path.symlink_to(outside_map)
            with self.assertRaisesRegex(RuntimeError, "symbolic link"):
                ingest.write_sidebar_order_state(
                    self.sidebar_order, map_path, docs_root, state_path=state_path
                )
            self.assertFalse(state_path.exists())

            netlify_path, static_path = self._redirect_fixture(root)
            outside_netlify = root / "outside-netlify.toml"
            outside_netlify.write_bytes(netlify_path.read_bytes())
            netlify_path.unlink()
            netlify_path.symlink_to(outside_netlify)
            before_docs = self._snapshot(docs_root)
            before_netlify = outside_netlify.read_bytes()
            with self.assertRaisesRegex(RuntimeError, "symbolic link"):
                ingest.reconcile_generated_outputs(
                    docs_root, netlify_path=netlify_path, static_path=static_path
                )
            self.assertEqual(self._snapshot(docs_root), before_docs)
            self.assertEqual(outside_netlify.read_bytes(), before_netlify)

            netlify_path.unlink()
            netlify_path.write_bytes(outside_netlify.read_bytes())
            outside_static = root / "outside-static.toml"
            outside_static.write_bytes(static_path.read_bytes())
            before_static = outside_static.read_bytes()
            static_path.unlink()
            static_path.symlink_to(outside_static)
            with self.assertRaisesRegex(RuntimeError, "symbolic link"):
                ingest.reconcile_generated_outputs(
                    docs_root, netlify_path=netlify_path, static_path=static_path
                )
            self.assertEqual(self._snapshot(docs_root), before_docs)
            self.assertEqual(outside_static.read_bytes(), before_static)

    def test_current_corpus_is_a_complete_fixed_point(self):
        generated_grids = self._generated_grids(self.source_docs)
        self.assertEqual(len(generated_grids), 33)

        with tempfile.TemporaryDirectory() as directory:
            docs_root = Path(directory) / "docs"
            shutil.copytree(self.source_docs, docs_root)
            state_path = Path(directory) / "state.json"
            self._write_state(docs_root, state_path, directory)
            expected = self._snapshot(docs_root)
            ingest.regenerate_grids_only(
                docs_root, state_path=state_path, netlify_path=None
            )
            self.assertEqual(self._snapshot(docs_root), expected)

    def test_real_device_metrics_grid_contains_every_integration_once(self):
        relative = Path(
            "Network Performance Monitoring/Device Metrics/Integrations"
        )
        integration_count = len(self._integration_files(self.source_docs, relative))
        pages = [
            path
            for path in self._generated_grids(self.source_docs / relative)
            if path.stem == "Integrations" or path.stem.startswith("Integrations Page ")
        ]
        cards = sum(
            path.read_text(encoding="utf-8").count("<Box ") for path in pages
        )
        self.assertEqual(integration_count, 179)
        self.assertEqual(len(pages), 2)
        self.assertEqual(cards, integration_count)

    def test_recovery_removes_grid_after_last_integration_is_removed(self):
        relative = Path(
            "Network Performance Monitoring/Syslog from Network Devices/Integrations"
        )

        def mutate(root):
            integrations = self._integration_files(root, relative)
            self.assertEqual(len(integrations), 1)
            integrations[0].unlink()

        self._assert_recovery_matches_clean_full(mutate)

    def test_recovery_replaces_disqualified_overview_with_generated_category(self):
        relative = Path(
            "Network Performance Monitoring/Syslog from Network Devices/Integrations"
        )

        def mutate(root):
            directory = root / relative
            for ordinal in range(2):
                (directory / f"Authored {ordinal}.mdx").write_text(
                    f"---\nsidebar_label: \"Authored {ordinal}\"\n---\n"
                    f"# Authored {ordinal}\n",
                    encoding="utf-8",
                )

        self._assert_recovery_matches_clean_full(mutate)

    def test_recovery_reconciles_pagination_shrink_and_growth(self):
        relative = Path(
            "Network Performance Monitoring/Device Metrics/Integrations"
        )

        def shrink(root):
            integrations = self._integration_files(root, relative)
            self.assertEqual(len(integrations), 179)
            for path in integrations[:5]:
                path.unlink()

        self._assert_recovery_matches_clean_full(shrink)

        def grow(root):
            integrations = self._integration_files(root, relative)
            source = integrations[0]
            for ordinal in range(172):
                self._copy_integration(
                    source,
                    root / relative / f"Recovery integration {ordinal}.mdx",
                    ordinal,
                )

        self._assert_recovery_matches_clean_full(grow)

    def test_recovery_replaces_generated_category_and_cleans_redirect_shadow(self):
        template = self._integration_files(
            self.source_docs,
            Path(
                "Network Performance Monitoring/Syslog from Network Devices/Integrations"
            ),
        )[0]

        def mutate_sources(root):
            directory = root / "Transition"
            directory.mkdir()
            (directory / "Note.mdx").write_text(
                '---\nsidebar_label: "Note"\n---\n# Note\n', encoding="utf-8"
            )
            for ordinal in range(2):
                self._copy_integration(
                    template,
                    directory / f"Recovery integration {ordinal}.mdx",
                    ordinal,
                )

        def mutate_recovery(root):
            directory = root / "Transition"
            for path in ingest._owned_grid_family(directory):
                path.unlink()
            (directory / "_category_.json").write_text(
                json.dumps(ingest._generated_category_payload("Transition", 10))
                + "\n",
                encoding="utf-8",
            )

        self._assert_recovery_matches_clean_full(
            mutate_sources, mutate_recovery=mutate_recovery
        )

    def test_recovery_repairs_corruption_without_overwriting_authored_pages(self):
        relative = Path(
            "Network Performance Monitoring/Syslog from Network Devices/Integrations"
        )

        def mutate_sources(root):
            authored_dir = root / "Curated"
            authored_dir.mkdir()
            authored = authored_dir / "Curated.mdx"
            authored.write_text(
                '---\nlearn_status: "AUTOGENERATED"\nslug: "/curated"\n---\n'
                "# Curated overview\n\nThis prose is intentionally curated.\n\n"
                "import { Grid } from '@site/src/components/Grid_integrations';\n",
                encoding="utf-8",
            )
            authored_page = authored_dir / "Curated Page 2.mdx"
            authored_page.write_text(
                authored.read_text(encoding="utf-8"), encoding="utf-8"
            )
            template = self._integration_files(root, relative)[0]
            self._copy_integration(
                template, authored_dir / "Recovery integration.mdx", 999
            )

        def mutate_recovery(root):
            grid = root / relative / "Integrations.mdx"
            grid.write_text(
                grid.read_text(encoding="utf-8") + "\nCORRUPTED\n",
                encoding="utf-8",
            )

        self._assert_recovery_matches_clean_full(
            mutate_sources, mutate_recovery=mutate_recovery
        )

    def test_sidebar_state_rejects_schema_provenance_and_corpus_drift(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            docs_root = root / "docs"
            shutil.copytree(self.source_docs, docs_root)
            state_path = root / "state.json"
            self._write_state(docs_root, state_path, root)
            valid = json.loads(state_path.read_text(encoding="utf-8"))
            checksum_path = ingest._sidebar_state_checksum_path(state_path)

            forged_source = json.loads(json.dumps(valid))
            forged_source["source_sha256"] = "0" * 64
            forged_source["full_ingest_identity_sha256"] = (
                ingest._sidebar_state_identity(forged_source)
            )
            state_path.write_text(json.dumps(forged_source), encoding="utf-8")
            with self.assertRaisesRegex(ValueError, "checksum"):
                ingest.load_sidebar_order_state(state_path, docs_root=docs_root)
            self._write_state(docs_root, state_path, root)

            checksum_path.unlink()
            with self.assertRaises(FileNotFoundError):
                ingest.load_sidebar_order_state(state_path, docs_root=docs_root)
            self._write_state(docs_root, state_path, root)

            checksum_path.write_text("not a checksum\n", encoding="utf-8")
            with self.assertRaisesRegex(ValueError, "checksum"):
                ingest.load_sidebar_order_state(state_path, docs_root=docs_root)
            self._write_state(docs_root, state_path, root)

            outside_checksum = root / "outside.sha256"
            outside_checksum.write_text("outside\n", encoding="utf-8")
            checksum_path.unlink()
            checksum_path.symlink_to(outside_checksum)
            with self.assertRaises(ingest.UnsafeFilesystemPathError):
                ingest.load_sidebar_order_state(state_path, docs_root=docs_root)
            checksum_path.unlink()
            checksum_path.mkdir()
            with self.assertRaises(ingest.UnsafeFilesystemPathError):
                ingest.load_sidebar_order_state(state_path, docs_root=docs_root)
            checksum_path.rmdir()
            self._write_state(docs_root, state_path, root)

            with self.assertRaises(FileNotFoundError):
                ingest.load_sidebar_order_state(
                    root / "missing.json", docs_root=docs_root
                )
            malformed_json = root / "malformed.json"
            malformed_json.write_text("not json", encoding="utf-8")
            self._write_matching_state_checksum(malformed_json)
            with self.assertRaises(json.JSONDecodeError):
                ingest.load_sidebar_order_state(
                    malformed_json, docs_root=docs_root
                )

            mutations = []
            missing_hash = json.loads(json.dumps(valid))
            missing_hash.pop("source_sha256")
            mutations.append(missing_hash)
            malformed_hash = json.loads(json.dumps(valid))
            malformed_hash["source_sha256"] = "bad"
            mutations.append(malformed_hash)
            extra_key = json.loads(json.dumps(valid))
            extra_key["unexpected"] = True
            mutations.append(extra_key)
            duplicate_entry = json.loads(json.dumps(valid))
            duplicate_entry["order"].append(duplicate_entry["order"][0])
            mutations.append(duplicate_entry)
            false_position = json.loads(json.dumps(valid))
            false_position["order"][0]["position"] = True
            mutations.append(false_position)
            wrong_identity = json.loads(json.dumps(valid))
            wrong_identity["full_ingest_identity_sha256"] = "0" * 64
            mutations.append(wrong_identity)

            for index, payload in enumerate(mutations):
                candidate = root / f"state-{index}.json"
                candidate.write_text(json.dumps(payload), encoding="utf-8")
                self._write_matching_state_checksum(candidate)
                with self.assertRaises(ValueError):
                    ingest.load_sidebar_order_state(candidate, docs_root=docs_root)

            source_file = next(
                path
                for path in docs_root.rglob("*.mdx")
                if not ingest._is_generated_grid_page(path)
            )
            source_file.write_text(
                source_file.read_text(encoding="utf-8") + "\nDRIFT\n",
                encoding="utf-8",
            )
            with self.assertRaisesRegex(ValueError, "does not match"):
                ingest.load_sidebar_order_state(state_path, docs_root=docs_root)


if __name__ == "__main__":
    unittest.main()
