import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path

import llms_files

INGEST_DIR = Path(__file__).resolve().parent
if str(INGEST_DIR) not in sys.path:
    sys.path.insert(0, str(INGEST_DIR))
spec = importlib.util.spec_from_file_location("learn_ingest", INGEST_DIR / "ingest.py")
ingest = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(ingest)

PRODUCT_DESCRIPTION_BODY = """# Netdata: Complete Product Description

## Executive Summary

Netdata is a distributed, real-time observability platform.
It runs everywhere.

Second paragraph.

## Platform

Uses \\<5% CPU, see [scalability](/docs/welcome-to-netdata/scalability#limits) and
[pricing](https://www.netdata.cloud/pricing/). Inline `\\{kept\\}` and <a href="/docs/x">x</a>.

```yaml
template: \\{kept\\}
link: /docs/not-a-link
```
"""


def front_matter(**fields):
    lines = ["---"]
    for key, value in fields.items():
        if value is True:
            lines.append(f"{key}: true")
        elif value is None:
            lines.append(f"{key}: null")
        else:
            lines.append(f'{key}: "{value}"')
    lines.append("---")
    return "\n".join(lines) + "\n\n"


def doc(slug, label, position, description=None, **extra):
    fields = {
        "custom_edit_url": f"https://github.com/netdata/netdata/edit/master/docs{slug}.md",
        "sidebar_label": label,
        "learn_status": "Published",
        "sidebar_position": position,
        "learn_link": f"https://learn.netdata.cloud/docs{slug}",
        "slug": slug,
    }
    if description:
        fields["description"] = description
    fields.update(extra)
    return front_matter(**fields) + f"# {label}\n"


class LlmsFilesTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.docs = Path(self.temporary.name) / "docs"
        pages = {
            "Getting Started.mdx": doc("/getting-started", "Getting Started", 30),
            "Live Demo.mdx": doc("/live-demo", "Live Demo", 40),
            "ask-nedi.mdx": front_matter(
                sidebar_label="Ask Nedi", sidebar_position=0, slug="/ask-nedi", part_of_learn=True
            ),
            "Welcome to Netdata/Welcome to Netdata.mdx": doc(
                "/welcome-to-netdata", "Welcome to Netdata", 20
            ),
            "Welcome to Netdata/Complete Product Description.mdx": front_matter(
                custom_edit_url="https://github.com/netdata/netdata/edit/master/docs/netdata-complete-product-description.md",
                sidebar_label="Complete Product Description",
                learn_status="Published",
                sidebar_position=10,
                learn_link="https://learn.netdata.cloud/docs/welcome-to-netdata/complete-product-description",
                slug="/welcome-to-netdata/complete-product-description",
                description="Everything Netdata does in one reference.",
            )
            + PRODUCT_DESCRIPTION_BODY,
            "Welcome to Netdata/Scalability.mdx": doc(
                "/welcome-to-netdata/scalability", "Scalability", 30, "How Netdata scales."
            ),
            "Netdata Agent/Netdata Agent.mdx": doc("/netdata-agent", "Netdata Agent", 50),
            "Netdata Agent/Configuration/Configuration.mdx": doc(
                "/netdata-agent/configuration", "Configuration", 20
            ),
            "Netdata Agent/Configuration/Daemon.mdx": doc(
                "/netdata-agent/configuration/daemon", "Daemon", 10, "netdata.conf [global] reference."
            ),
            "Netdata Agent/Logging.mdx": doc("/netdata-agent/logging", "Logging", 10),
            "Collecting Metrics/Collecting Metrics.mdx": doc(
                "/collecting-metrics", "Collecting Metrics", 90
            ),
            "Collecting Metrics/Collectors/Collectors.mdx": front_matter(
                sidebar_label="Collectors",
                sidebar_position=10,
                learn_status="AUTOGENERATED",
                generated_grid_page=True,
                custom_edit_url=None,
                slug="/collecting-metrics/collectors",
                learn_link="https://learn.netdata.cloud/docs/collecting-metrics/collectors",
                description="Browse collectors.",
            ),
            "Collecting Metrics/Collectors/Collectors Page 2.mdx": front_matter(
                sidebar_label="Collectors (page 2)",
                sidebar_class_name="generated-pagination-page",
                learn_status="AUTOGENERATED",
                generated_grid_page=True,
                custom_edit_url=None,
                slug="/collecting-metrics/collectors/page/2",
                learn_link="https://learn.netdata.cloud/docs/collecting-metrics/collectors/page/2",
            ),
            "Collecting Metrics/Collectors/Apache.mdx": doc(
                "/collecting-metrics/collectors/apache",
                "Apache",
                10,
                message="DO NOT EDIT THIS FILE DIRECTLY, IT IS GENERATED BY THE COLLECTOR'S metadata.yaml FILE",
            ),
        }
        for name, content in pages.items():
            path = self.docs / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)

    def tearDown(self):
        self.temporary.cleanup()

    def test_full_file_is_the_product_description_as_plain_markdown(self):
        _, full = llms_files.build_llms_files(self.docs)
        self.assertTrue(full.startswith("# Netdata: Complete Product Description\n"))
        self.assertNotIn("custom_edit_url", full)
        self.assertIn("Uses <5% CPU", full)
        self.assertIn(
            "[scalability](https://learn.netdata.cloud/docs/welcome-to-netdata/scalability#limits)",
            full,
        )
        self.assertIn("[pricing](https://www.netdata.cloud/pricing/)", full)
        self.assertIn('<a href="https://learn.netdata.cloud/docs/x">', full)
        self.assertIn("Inline `\\{kept\\}`", full)
        self.assertIn("template: \\{kept\\}\nlink: /docs/not-a-link\n", full)
        self.assertTrue(full.endswith("```\n"))

    def test_index_follows_the_sidebar_and_lists_catalogs_once(self):
        index, _ = llms_files.build_llms_files(self.docs)
        self.assertTrue(
            index.startswith(
                "# Netdata\n\n> Netdata is a distributed, real-time observability platform. "
                "It runs everywhere.\n\n"
            )
        )
        sections = [line for line in index.splitlines() if line.startswith("## ")]
        self.assertEqual(
            sections,
            [
                "## Complete Product Description",
                "## Welcome to Netdata",
                "## Getting Started",
                "## Live Demo",
                "## Netdata Agent",
                "## Collecting Metrics",
            ],
        )
        entries = [line for line in index.splitlines() if line.startswith("- [")]
        self.assertEqual(
            entries,
            [
                "- [Complete Product Description](https://learn.netdata.cloud/llms-full.txt): "
                "Everything Netdata does in one reference.",
                "- [Complete Product Description web page]"
                "(https://learn.netdata.cloud/docs/welcome-to-netdata/complete-product-description)",
                "- [Welcome to Netdata](https://learn.netdata.cloud/docs/welcome-to-netdata)",
                "- [Scalability](https://learn.netdata.cloud/docs/welcome-to-netdata/scalability): "
                "How Netdata scales.",
                "- [Getting Started](https://learn.netdata.cloud/docs/getting-started)",
                "- [Live Demo](https://learn.netdata.cloud/docs/live-demo)",
                "- [Netdata Agent](https://learn.netdata.cloud/docs/netdata-agent)",
                "- [Logging](https://learn.netdata.cloud/docs/netdata-agent/logging)",
                "- [Configuration](https://learn.netdata.cloud/docs/netdata-agent/configuration)",
                "- [Configuration › Daemon]"
                "(https://learn.netdata.cloud/docs/netdata-agent/configuration/daemon): "
                "netdata.conf [global] reference.",
                "- [Collecting Metrics](https://learn.netdata.cloud/docs/collecting-metrics)",
                "- [Collectors](https://learn.netdata.cloud/docs/collecting-metrics/collectors): "
                "Browse collectors.",
            ],
        )

    def test_full_file_restores_text_that_ingest_escaped_as_prose(self):
        # MDX has no indented code, and ingest escapes braces in code spans that cross lines
        # like prose, so llms-full.txt undoes those escapes too and gets the source text back.
        source = (
            "Set {name} here.\n\n"
            "    an indented {line} is a paragraph in MDX\n\n"
            "A `multi-line\ncode {span}` example.\n\n"
            "```yaml\nkey: {value}\n```\n"
        )
        escaped = ingest._escape_mdx_braces(source)
        self.assertNotEqual(escaped, source)
        self.assertEqual(llms_files.llms_full_text(escaped), source)

    def test_index_skips_integration_pages_marked_outside_the_message(self):
        # Ingest treats any file containing the marker as a generated integration page.
        (self.docs / "Collecting Metrics/Collectors/Nginx.mdx").write_text(
            doc("/collecting-metrics/collectors/nginx", "Nginx", 20)
            + "\n<!-- DO NOT EDIT THIS FILE DIRECTLY, IT IS GENERATED BY THE COLLECTOR'S "
            "metadata.yaml FILE -->\n"
        )
        index, _ = llms_files.build_llms_files(self.docs)
        self.assertNotIn("/docs/collecting-metrics/collectors/nginx", index)
        self.assertEqual(llms_files.GENERATED_INTEGRATION_MARKER, ingest.INTEGRATION_MARKER)

    def test_missing_product_description_leaves_the_files_alone(self):
        (self.docs / "Welcome to Netdata/Complete Product Description.mdx").unlink()
        self.assertIsNone(llms_files.build_llms_files(self.docs))


if __name__ == "__main__":
    unittest.main()
