name: Check URLs

on: [push, pull_request]

jobs:

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@0.6.0
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        # config-file: 'mlc_config.json'
        folder-path: 'docs/'